apiVersion: v1
description: A Helm chart to deploy the artemis web platoform
name: artemis Deployment
version: 0.0.1
home: fuchicorp.com
source:
  - https://github.com/fuchicorp/artemis
engine: gotpl
icon: https://avatars0.githubusercontent.com/u/46357473?s=400&u=6b8b91915948a9a0a4c848b5d4559b3db025fccc&v=4
maintainers:
  - name: Caglar Cavdar
    email: chaglare@gmail.com
keywords:
  - ingress
